/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#00685f',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#ecf1ff',
        'secondary-container': '#d8e5e2',
        'on-secondary-fixed-variant': '#3d4947',
        'primary-fixed': '#89f5e7',
        'surface-dim': '#cfdaf2',
        'surface-variant': '#d8e3fb',
        'surface-tint': '#006a61',
        'on-primary-container': '#f4fffc',
        'surface-container-low': '#f0f3ff',
        'on-error-container': '#93000a',
        'inverse-primary': '#6bd8cb',
        'on-primary-fixed': '#00201d',
        'surface-container': '#e7eeff',
        'on-tertiary-fixed': '#00201c',
        'surface-bright': '#f9f9ff',
        'secondary-fixed': '#d8e5e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dee8ff',
        'error-container': '#ffdad6',
        'on-surface-variant': '#3d4947',
        outline: '#6d7a77',
        'on-tertiary-container': '#f4fffb',
        'on-secondary': '#ffffff',
        'primary-container': '#008378',
        'tertiary-fixed': '#62fae3',
        error: '#ba1a1a',
        'primary-fixed-dim': '#6bd8cb',
        'on-secondary-container': '#5b6765',
        'on-primary': '#ffffff',
        'surface-container-highest': '#d8e3fb',
        'inverse-surface': '#263143',
        secondary: '#55615f',
        'secondary-fixed-dim': '#bcc9c6',
        background: '#f9f9ff',
        'on-background': '#111c2d',
        'on-primary-fixed-variant': '#005049',
        'tertiary-fixed-dim': '#3cddc7',
        tertiary: '#00685c',
        'on-error': '#ffffff',
        'on-surface': '#111c2d',
        'on-secondary-fixed': '#121e1c',
        'on-tertiary-fixed-variant': '#005047',
        'tertiary-container': '#008375',
        surface: '#f9f9ff',
        'outline-variant': '#bcc9c6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        xs: '4px',
        sm: '8px',
        'container-max': '1440px',
        'margin-mobile': '16px',
        unit: '4px',
        'margin-desktop': '32px',
        gutter: '24px',
        xl: '48px',
        md: '16px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk'],
        'label-md': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'title-md': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'body-sm': ['Hanken Grotesk'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', fontWeight: '600' },
        ],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
};
